### ISSUE TITLE
Divide by 0 Error

### ISSUE THREAD

**Issue by dfmartin43** [vangj/py-bbn#10]
When I called from_data in the pybbn.graph.factory class on my dataset, it gave a divide by zero error. There is a line that is 
`prob = numer / denom`, which is numerically unstable. I changed it to `prob = numer / (denom + 0.00001)` to get the code to run. I think this would be a good improvement for your project because adding a small value to denominators is generally used for stability purposes. Thanks

**Comment by vangj** [comment]
https://github.com/vangj/py-bbn/commit/e333651c1e9182e512d4be2ee2b7db1c8468a07c
