### ISSUE TITLE
PPTC implementation returns incorrect probabilities

### ISSUE THREAD

**Issue by dante-ga** [vangj/py-bbn#4]
Hello! I've noticed that on a medium sized graph PPTC implementation in this library reurns incorrect probabilities. Here is the simplest version of the network which showcases the problem.
```json
[
  {"id":"A","states":["T","F"],"parents":[],"cpt":[0.5,0.5]},
  {"id":"B","states":["T","F"],"parents":["A"],"cpt":[0.2,0.8,0.1,0.9]},
  {"id":"C","states":["T","F"],"parents":["A"],"cpt":[0.5,0.5,0.5,0.5]},
  {"id":"D","states":["T","F"],"parents":["B"],"cpt":[0.5,0.5,0.5,0.5]},
  {"id":"E","states":["T","F"],"parents":["B"],"cpt":[0.5,0.5,0.5,0.5]},
  {"id":"F","states":["T","F"],"parents":["C"],"cpt":[0.5,0.5,0.5,0.5]},
  {"id":"G","states":["T","F"],"parents":["E","D","F"],"cpt":[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]},
]
```

The implementation calculates the following probabilities:
```json
{
  "A": 0.5686274509803922,
  "B": 0.5000000000000001,
  "C": 0.5,
  "D": 0.5,
  "E": 0.5,
  "F": 0.5,
  "G": 0.5,
}
```

However I expect the probabilities to be:
```json
{
  "A": 0.5,
  "B": 0.15,
  "C": 0.5,
  "D": 0.5,
  "E": 0.5,
  "F": 0.5,
  "G": 0.5,
}
```
Could you please fix this bug?
Every implemetation I tried so far had a serious issue with it 😢

**Comment by vangj** [comment]
See https://github.com/vangj/py-bbn/blob/master/tests/pptc/test_inferencecontroller.py#L30.

There was a serious bug in the collect and distribute evidence implementation. Instead of passing (clique, sepSet, clique) we were always passing in (startClique, sepSet, clique). How it got this far was just "luck". Hope this helps.
