### ISSUE TITLE
Linear Gaussian Inference on Evidence

### ISSUE THREAD

**Issue by ostwalprasad** [vangj/py-bbn#5]
Firstly, many thanks for writting this module. It's quite helpful!

I've been playing around with LGs for past week with this module. I wanted to know which paper/book was followed for Linear Gaussian Inference ( src>lg>graph.py) particularly 
predict_proba() code. I found [this](https://cedar.buffalo.edu/~srihari/CSE674/Chap7/7.2-GaussBNs.pdf)  one similar. Also, l couldn't find any docs/example for lg>gaussian and lg>inference. 

It would be grateful if you could add reference links for gaussian models.

Also, I tried do_inference() function to get inference using conditioned variable :

I created a small network : Node0>Node1>Node2
```
# Create Toy data in pandas dataframe

df = pd.DataFrame()
length=99
df['a'] = np.linspace(0,50,length) + np.random.normal(0,2,length)
df['b'] = (3*df['a'])  + np.random.normal(0,2,length)
df['d'] = (2*df['b']) + np.random.normal(0,2,length)

# Calculate covariance and mean of dataframe
cov = np.array(df.cov())
mean = np.array(df.mean())

#Create Network
dag1 = Dag()
dag1.add_node(0,metadata={'name':'A'})
dag1.add_node(1,metadata={'name':'B'})
dag1.add_node(2,metadata={'name':'D'})
dag1.add_edge(0, 1)
dag1.add_edge(1, 2)

# The parameters are estimated from the samples above
params = Parameters(mean, cov)

# create the bayesian belief network
bbn1 = Bbn(dag1, params)
```
These are the means and covariances for the data
```
mean  = array([ 24.79494819,  74.44707958, 148.96799903])
cov = array([[ 220.64004318,  662.35310334, 1321.52335555],
       [ 662.35310334, 1991.98019528, 3974.13546903],
       [1321.52335555, 3974.13546903, 7933.38989638]])
```
Now, when I condition on Node2(Which is child of Node 1), I get following means and covariances.
```
bbn1.clear_evidences()
bbn1.set_evidence(2,100)
mean_c,cov_c =  bbn1.do_inference()
```
```
array([ 16.63798689,  49.91715425, 100.])
array([[5.04136325e-01, 3.52003045e-01, 1.32152336e+03],
       [3.52003045e-01, 1.18522207e+00, 3.97413547e+03],
       [1.32152336e+03, 3.97413547e+03, 1.00000000e-02]])
```
Now, as network has hierarchy like Node0>Node1>Node2, evidence on Node 2 shouldn't change the means of Node0 and Node1. I tried putting evidence on Node 1 as well and it also changed values of both Node0 and Node2. Seems like there's no d-separation.

I saw source code and found out that network structure is not being utlized to find out values, rather conditionals are calculated directly using block matrices (function __compute_means__() and __compute_covs__() ) . Shouldn't Linear Gaussian network consider network hirarchy as well like in [ this ](https://cedar.buffalo.edu/~srihari/CSE674/Chap7/7.2-GaussBNs.pdf )presentation slide 11-12?

Thanks again! 

_Edit: Added example code._

**Comment by vangj** [comment]
You are correct. Please do not use the implementation for linear gaussian yet. It is experimental. I might remove it from the API altogether.

**Comment by ostwalprasad** [comment]
Thanks for reply @vangj. In the meantime I built a module for Linear Gaussian myself here [LGNpy](https://github.com/ostwalprasad/LGNpy) . It's still experimental, Can you have a look?

**Comment by vangj** [comment]
Awesome! I'll take a look. I was able to understand how message passing works with LGN's. I blogged about it here: https://datascience.oneoffcoder.com/gaussian-network-inference.html. The difference is in the way the potentials are represented and how evidence is injected into the junction tree. When I have time I will try to implement it.
