### ISSUE TITLE
pybbn updating wrong result

### ISSUE THREAD

**Issue by Lin-jun-xiang** [vangj/py-bbn#7]
I'm try to use pybbn update by ".reaply"

However, after update, i get wrong answer.

before update:
analysis solution >> P(clay_till=F)=0.625*1*1*0.6 + 0.125*1*1*0.4 = 0.425 
pybbn return 0.425 >> get right answer

after update:
analysis solution >> P(clay_till=F)=0.8125*1*1*0.6 + 0.3125*1*1*0.4 = 0.6125
pybbn return 0.55 >> get wrong answer

i will upload the code, cpt table, bnn structure.

p.s. what different between ".with_evidence" and ".reaply" 

thank for reading.
[PyBbn.zip](https://github.com/vangj/py-bbn/files/6769181/PyBbn.zip)

**Comment by vangj** [comment]
Try the latest version. I think this problem is fixed. Here's the output against the latest version.

```bash
before update
f2 : l=0.00000, lm=1.00000
f3 : F=0.60000, U=0.40000
clay till : F=0.42500, U=0.57500
f1 : h=0.00000, no=1.00000

after update
f2 : l=0.00000, lm=1.00000
f3 : F=0.60000, U=0.40000
clay till : F=0.61250, U=0.38750
f1 : h=1.00000, no=0.00000
```
