### ISSUE TITLE
pybnn .EvidenceBuilder() /.with_evidence function not providing same results

### ISSUE THREAD

**Issue by rafmora** [vangj/py-bbn#8]
The .EvidenceBuilder() /.with_evidence did not provide the same results with the same observation.
I have used the data from the paper "BBN: Bayesian Belief Networks — How to Build Them Effectively in Python" at https://towardsdatascience.com/bbn-bayesian-belief-networks-how-to-build-them-effectively-in-python-6b7f93435bba 

The predicted value based on an observation changed from the original value (no observation) to the  expected value (with observation), as expected. However, If repeated the function "predict", it goes back to the original value.

def posterior_res(jt):
  for node, posteriors in jt.get_posteriors().items():
    p = ', '.join([f'{val}={prob:.5f}' for val, prob in posteriors.items()])
    print(f'{node} : {p}')
  return
def predict(jt, formula, node_var, obsv, prob_obsv):
  formula = EvidenceBuilder() \
  .with_node(jt.get_bbn_node_by_name(node_var)) \
  .with_evidence(obsv, prob_obsv) \
  .build()

  jt.set_observation(formula)
  return

predict(join_tree, 'H9am_obsv', 'Humidity9am', "High_>60", 1)
posterior_res(join_tree)

Your assistance is appreciated.

**Comment by vangj** [comment]
You need to format your code. How are we supposed to read that code? 

Call join_tree.unobserve_all()
